env:
  commonjs: true
  es6: true
  node: true
extends: airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  module: true
  global: true
  require: true
parserOptions:
  ecmaVersion: 2019
  sourceType: module
plugins: [flowtype, babel, jsx-a11y, sort-imports-es6-autofix]
parser: babel-eslint
rules:
  no-unused-vars: 1
  no-console: 1
  import/order: ["warn", { "newlines-between": "always" }]
  sort-imports-es6-autofix/sort-imports-es6: 1
  max-classes-per-file: 0
