env:
  commonjs: true
  es6: true
  node: true
extends: airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  module: true
  global: true
  require: true
parserOptions:
  ecmaVersion: 2019
  sourceType: module
plugins: [flowtype, babel, jsx-a11y]
parser: babel-eslint
rules:
  no-unused-vars: 1
  no-console: 1
  import/order:
    [
      warn,
      {
        newlines-between: always,
        alphabetize: { order: desc, caseInsensitive: true },
      },
    ]
  max-classes-per-file: 0
